# Generated by Django 5.2.6 on 2025-12-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0017_merge_20251210_1725'),
        ('medicamentos', '0018_merge_20251212_1406'),
    ]

    operations = [
    ]
