# Generated by Django 5.2.6 on 2025-12-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0018_merge_20251215_1842'),
        ('medicamentos', '0019_merge_20251213_1315'),
    ]

    operations = [
    ]
